### ISSUE TITLE
Styling not applied to emphasize-lines text in literalinclude directives

### ISSUE THREAD

**Issue by inkybutton** [OpenCMISS/website#46]
OpenCMISS documentation uses ReST's literalinclude directive to show code from an external source file inline. The directive includes a parameter(emphasize-lines) that allows particular lines from the source file to be emphasised. In other Sphinx themes, the emphasised lines are displayed with a bright background colour in order to highlight them. In the custom theme for the OpenCMISS website there is no styling applied which means the lines do not stand out. https://github.com/OpenCMISS/documentation/blob/develop/data_format/fieldml/tetmesh.rst is one of the documentation pages affected.

## Steps to Reproduce
1. Visit http://opencmiss.org/documentation/data_format/fieldml/tetmesh.html
2. Look at the first inline source area.

## Expected Result
Lines 18 - 20, 53 - 55, and other lines should be shown in a different style in contrast to other lines.

## Actual Result
They look the same as other lines.

**Comment by hsorby** [comment]
Closing with PR #47.
