### ISSUE TITLE
OpenCMISS-Iron API documentation is out-of-date

### ISSUE THREAD

**Issue by inkybutton** [OpenCMISS/website#55]
The OpenCMISS-Iron API documentation hasn't been updated since December 2016. This is caused by the migration of the OpenCMISS build system from Buildbot/make to Jenkins/CMake.
After discussion at last week's OpenCMISS meeting, it was decided that we will generate the documentation as part of the website build process.

**Comment by inkybutton** [comment]
Currently waiting for IT to upgrade the VM, so that the new Iron API documentation build can happen. The relevant person is due back on Wednesday. cc @chrispbradley

**Comment by inkybutton** [comment]
I have now spoken to IT and also @hsorby - turns out the software team would like to keep the VM at the current version. This means I will need to migrate the website build to another VM that does run Ubuntu 16.04. I can also take this as an opportunity to try change the website build system to Jenkins, which is used by other OpenCMISS projects. The website build is currently running on an old, forked version of Buildbot, which has a few quirks. Changing to Jenkins would probably make it easier to maintain in the long term.
Let me know if you're happy with this @chrispbradley.

**Comment by chrispbradley** [comment]
Hi Noel, sure, move and update to Jenkins. Is the Jenkins update a quick job? If long is there anything that can be done to get something going in the interim?

**Comment by inkybutton** [comment]
Yes I think the migration to Jenkins might take some time. I can set up the new VM as a buildbot builder for now and then disable it when migration to Jenkins is complete - that should be quicker.

**Comment by chrispbradley** [comment]
Sounds like a plan.

**Comment by inkybutton** [comment]
Buildbot has been set up on the new VM and it's now able to make a build successfully. Please see staging.opencmiss.org/documentation.html for the build result. I will now create a PR to merge changes into master (i.e. www.opencmiss.org), please OK it if you're happy with the generated API documentation.

**Comment by inkybutton** [comment]
The Iron API docs are now kept up-to-date. I will close this issue now and track migration of the website build to Jenkins as a separate issue.
